
### Get all user
GET http://localhost:5500/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcwMzliZjI2ZWRjOTMyYTFiMWUwMDkiLCJpYXQiOjE2MzQ3NDQ4MjF9.9yAQvnER0Etev0_r1zgBWCEno-JhEYuOScIBYPYuvuc

### Register
POST http://localhost:5500/api/auth/register
Content-Type: application/json

{
  "name": "abc",
  "email":"abc@mail.com",
  "password": "abc"
}

### Login
POST http://localhost:5500/api/auth/login
Content-Type: application/json

{
  "email": "teo2@mail.com",
  "password": "teo2"
}

### Logout 



### Add post


### Get all post
GET http://localhost:5500/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyYjA1MDUzYmJjNGM3Mjc3OTY5ZmMiLCJpYXQiOjE2MzQ5MTA3ODEsImV4cCI6MTYzNDkxMDg0MX0.u4vqaiN4EEVTz1eEe-xC9TDMu9uy_khanRZuPjN7YfU

### Update post by user id
PUT http://localhost:5500/api/posts/61703a2c159784aeebdc3b66
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcwMzliZjI2ZWRjOTMyYTFiMWUwMDkiLCJpYXQiOjE2MzQ3NDQ4MjF9.9yAQvnER0Etev0_r1zgBWCEno-JhEYuOScIBYPYuvuc

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

### Delete post by user id
DELETE http://localhost:5500/api/posts/61703a2c159784aeebdc3b66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcwMzliZjI2ZWRjOTMyYTFiMWUwMDkiLCJpYXQiOjE2MzQ3NDQ4MjF9.9yAQvnER0Etev0_r1zgBWCEno-JhEYuOScIBYPYuvuc

### test user Suggestion
GET http://localhost:5500/api/users/user-suggestions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTczODAzODRjMTU4YTZkNWU0MjdmM2EiLCJpYXQiOjE2MzQ5OTgyNzZ9.K1v6cVA3W1mjP1JTDttvZb-VpaR4JaVtloNUFmZ9msE
