### duc1 followwwwwwwwwwwwwwwww duc2
### Bearer accessToken
PUT http://localhost:5500/users/follow_and_unfollow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzUzNTgxNjd9.jYBa8hQeoFu6QO7PAcSClkd3BsAR_EWMjZUQ2x121QM

{
  "userIdFollow":"61796a42a47a2f0cba34a7f2",
  "userIdBeFollow":"61796a43a47a2f0cba34a7f5"
}