### Bearer accessToken
POST http://localhost:5500/posts/add/617aca645d061dfe08b9c2d9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTdhY2E2NzVkMDYxZGZlMDhiOWMyZGYiLCJpYXQiOjE2MzU0MzcxNTl9.TRMU9oDNINeEHP2Z_LzpCeOhQ8kKI9xg0n1i4k-RVR8