### Bearer accessToken
PUT http://localhost:5500/posts/dislike
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTdiNGEwNjhhNDMwNjczODQ5MzJlMzAiLCJpYXQiOjE2MzU1MDc0MTB9.bSVsGV5rGkXgOTbr6rI2b00gDeDCvNSkqqToG4NSw6c

{
  "userId":"617b4a068a43067384932e30",
  "postId":"617b4db88a43067384932e77"
}